const SampleVideos = [
  {
    id: 'sXxbkjlHvf4',
    thumbnail: 'https://i.ytimg.com/vi/sXxbkjlHvf4/mqdefault.jpg',
    title: 'OREO MEME',
    author: 'NYE SAVE CHANNEL',
    views: '15989211',
    likes: '371533',
    iframe: "<iframe src='https://youtube.com/embed/sXxbkjlHvf4' \n                frameborder=\"0\" \n                allow=\"accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture\" \n                allowfullscreen \n                title=OREO MEME</iframe>",
    dateAdded: '2010-11-20T06:24:12+01:00',
    platform: 'YouTube',
    url: 'https://youtube.com/sXxbkjlHvf4',
    isFavorite: true,
  },
  {
    id: 'M9QT7CmuJYM',
    thumbnail: 'https://i.ytimg.com/vi/M9QT7CmuJYM/mqdefault.jpg',
    title: 'HALLOWEEN EDM PARTY MIX 2020 - Best Electro House & Future House Charts Music',
    author: 'daveepa',
    views: '4732554',
    likes: '58376',
    iframe: "<iframe src='https://youtube.com/embed/M9QT7CmuJYM' \n                frameborder=\"0\" \n                allow=\"accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture\" \n                allowfullscreen \n                title=HALLOWEEN EDM PARTY MIX 2020 - Best Electro House & Future House Charts Music</iframe>",
    dateAdded: '2013-03-15T04:53:49+01:00',
    platform: 'YouTube',
    url: 'https://youtube.com/M9QT7CmuJYM',
    isFavorite: false,
  },
  {
    id: '532952738',
    thumbnail: 'https://i.vimeocdn.com/video/1103238895_295x166.jpg?r=pad',
    title: "He's the One",
    author: 'Topic',
    views: 'Unknown',
    likes: 168,
    iframe: '<iframe src="https://player.vimeo.com/video/532952738?badge=0&amp;autopause=0&amp;player_id=0&amp;app_id=210503" width="1920" height="1080" frameborder="0" allow="autoplay; fullscreen; picture-in-picture" allowfullscreen title="He&amp;#039;s the One"></iframe>',
    dateAdded: '2019-10-15T12:00:25+02:00',
    platform: 'Vimeo',
    url: 'https://vimeo.com/topicstories/hestheone',
    isFavorite: true,
  },
  {
    id: 'wofz0k6FCMU',
    thumbnail: 'https://i.ytimg.com/vi/wofz0k6FCMU/mqdefault.jpg',
    title: "The shortest game of Magnus Carlsen's chess career!",
    author: 'ChessBase India',
    views: '43419964',
    likes: '409202',
    iframe: "<iframe src='https://youtube.com/embed/wofz0k6FCMU' \n                frameborder=\"0\" \n                allow=\"accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture\" \n                allowfullscreen \n                title=The shortest game of Magnus Carlsen's chess career!</iframe>",
    dateAdded: '2020-05-22T04:34:47+02:00',
    platform: 'YouTube',
    url: 'https://youtube.com/wofz0k6FCMU',
    isFavorite: false,
  },
  {
    id: '533757272',
    thumbnail: 'https://i.vimeocdn.com/video/1105089922_295x166.jpg?r=pad',
    title: 'Manila is Full of Men Named Boy',
    author: 'Andrew Stephen Lee',
    views: 'Unknown',
    likes: 156,
    iframe: '<iframe src="https://player.vimeo.com/video/533757272?badge=0&amp;autopause=0&amp;player_id=0&amp;app_id=210503" width="1920" height="1080" frameborder="0" allow="autoplay; fullscreen; picture-in-picture" allowfullscreen title="Manila is Full of Men Named Boy"></iframe>',
    dateAdded: '2011-03-16T10:39:50+01:00',
    platform: 'Vimeo',
    url: 'https://vimeo.com/533757272',
    isFavorite: false,
  },
  {
    id: 'dKFUgnMjkzE',
    thumbnail: 'https://i.ytimg.com/vi/dKFUgnMjkzE/mqdefault.jpg',
    title: 'BEANOS',
    author: 'Pukekura',
    views: '4200021',
    likes: '78365',
    iframe: "<iframe src='https://youtube.com/embed/dKFUgnMjkzE' \n                frameborder=\"0\" \n                allow=\"accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture\" \n                allowfullscreen \n                title=BEANOS</iframe>",
    dateAdded: '2013-02-01T11:40:42+01:00',
    platform: 'YouTube',
    url: 'https://youtube.com/dKFUgnMjkzE',
    isFavorite: true,
  },
  {
    id: '_8sx8OJGDoQ',
    thumbnail: 'https://i.ytimg.com/vi/_8sx8OJGDoQ/mqdefault.jpg',
    title: 'elmo moto moto',
    author: 'ironic.mp4',
    views: '6618855',
    likes: '255069',
    iframe: "<iframe src='https://youtube.com/embed/_8sx8OJGDoQ' \n                frameborder=\"0\" \n                allow=\"accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture\" \n                allowfullscreen \n                title=elmo moto moto</iframe>",
    dateAdded: '2014-12-15T00:33:10+01:00',
    platform: 'YouTube',
    url: 'https://youtube.com/_8sx8OJGDoQ',
    isFavorite: true,
  },
  {
    id: 'WdBldz3YLss',
    thumbnail: 'https://i.ytimg.com/vi/WdBldz3YLss/mqdefault.jpg',
    title: 'New Year Mix 2021 - Best of EDM Party Electro House & Festival Music',
    author: 'ElectroDanceMixes',
    views: '2964381',
    likes: '27993',
    iframe: "<iframe src='https://youtube.com/embed/WdBldz3YLss' \n                frameborder=\"0\" \n                allow=\"accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture\" \n                allowfullscreen \n                title=New Year Mix 2021 - Best of EDM Party Electro House & Festival Music</iframe>",
    dateAdded: '2009-06-04T04:23:42+02:00',
    platform: 'YouTube',
    url: 'https://youtube.com/WdBldz3YLss',
    isFavorite: false,
  },
  {
    id: '528617116',
    thumbnail: 'https://i.vimeocdn.com/video/1098857251_295x166.jpg?r=pad',
    title: 'WE ARE: A Visual Mission Statement from Jon Batiste',
    author: 'Bram VanderMark',
    views: 'Unknown',
    likes: 67,
    iframe: '<iframe src="https://player.vimeo.com/video/528617116?badge=0&amp;autopause=0&amp;player_id=0&amp;app_id=210503" width="1920" height="1080" frameborder="0" allow="autoplay; fullscreen; picture-in-picture" allowfullscreen title="WE ARE: A Visual Mission Statement from Jon Batiste"></iframe>',
    dateAdded: '2021-02-08T14:36:48+01:00',
    platform: 'Vimeo',
    url: 'https://vimeo.com/528617116',
    isFavorite: true,
  },
  {
    id: '265793714',
    thumbnail: 'https://i.vimeocdn.com/video/996279864_295x166.jpg?r=pad',
    title: 'HOLE',
    author: 'g. goletski',
    views: 'Unknown',
    likes: 275,
    iframe: '<iframe src="https://player.vimeo.com/video/265793714?badge=0&amp;autopause=0&amp;player_id=0&amp;app_id=210503" width="1920" height="1080" frameborder="0" allow="autoplay; fullscreen; picture-in-picture" allowfullscreen title="HOLE"></iframe>',
    dateAdded: '2016-02-14T22:58:19+01:00',
    platform: 'Vimeo',
    url: 'https://vimeo.com/265793714',
    isFavorite: true,
  },
  {
    id: 'BubwLnPcQjc',
    thumbnail: 'https://i.ytimg.com/vi/BubwLnPcQjc/mqdefault.jpg',
    title: 'New Year Mix 2020 - Best of EDM Party Electro House & Festival Music',
    author: 'ElectroDanceMixes',
    views: '16888799',
    likes: '148880',
    iframe: "<iframe src='https://youtube.com/embed/BubwLnPcQjc' \n                frameborder=\"0\" \n                allow=\"accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture\" \n                allowfullscreen \n                title=New Year Mix 2020 - Best of EDM Party Electro House & Festival Music</iframe>",
    dateAdded: '2019-01-03T09:36:51+01:00',
    platform: 'YouTube',
    url: 'https://youtube.com/BubwLnPcQjc',
    isFavorite: true,
  },
  {
    id: '530671012',
    thumbnail: 'https://i.vimeocdn.com/video/1098419706_295x166.jpg?r=pad',
    title: "What's On Your Mind Music Video",
    author: 'Qianhui Yu',
    views: 'Unknown',
    likes: 51,
    iframe: '<iframe src="https://player.vimeo.com/video/530671012?badge=0&amp;autopause=0&amp;player_id=0&amp;app_id=210503" width="1920" height="1080" frameborder="0" allow="autoplay; fullscreen; picture-in-picture" allowfullscreen title="What&amp;#039;s On Your Mind Music Video"></iframe>',
    dateAdded: '2019-02-18T02:34:39+01:00',
    platform: 'Vimeo',
    url: 'https://vimeo.com/530671012',
    isFavorite: false,
  },
  {
    id: 'lTRiuFIWV54',
    thumbnail: 'https://i.ytimg.com/vi/lTRiuFIWV54/mqdefault.jpg',
    title: '1 A.M Study Session 📚 - [lofi hip hop/chill beats]',
    author: 'Lofi Girl',
    views: '43932544',
    likes: '956309',
    iframe: "<iframe src='https://youtube.com/embed/lTRiuFIWV54' \n                frameborder=\"0\" \n                allow=\"accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture\" \n                allowfullscreen \n                title=1 A.M Study Session 📚 - [lofi hip hop/chill beats]</iframe>",
    dateAdded: '2011-10-26T18:37:44+02:00',
    platform: 'YouTube',
    url: 'https://youtube.com/lTRiuFIWV54',
    isFavorite: true,
  },
  {
    id: 'TcUfUkYsGq0',
    thumbnail: 'https://i.ytimg.com/vi/TcUfUkYsGq0/mqdefault.jpg',
    title: 'I can ＦＩＸ ＩＴ',
    author: 'Bosh',
    views: '6714240',
    likes: '155308',
    iframe: "<iframe src='https://youtube.com/embed/TcUfUkYsGq0' \n                frameborder=\"0\" \n                allow=\"accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture\" \n                allowfullscreen \n                title=I can ＦＩＸ ＩＴ</iframe>",
    dateAdded: '2014-11-08T21:00:29+01:00',
    platform: 'YouTube',
    url: 'https://youtube.com/TcUfUkYsGq0',
    isFavorite: false,
  },
  {
    id: 'pW_Z67R53XA',
    thumbnail: 'https://i.ytimg.com/vi/pW_Z67R53XA/mqdefault.jpg',
    title: 'Stranger Cats',
    author: 'EvinEdits',
    views: '11470194',
    likes: '381478',
    iframe: "<iframe src='https://youtube.com/embed/pW_Z67R53XA' \n                frameborder=\"0\" \n                allow=\"accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture\" \n                allowfullscreen \n                title=Stranger Cats</iframe>",
    dateAdded: '2014-04-29T20:09:39+02:00',
    platform: 'YouTube',
    url: 'https://youtube.com/pW_Z67R53XA',
    isFavorite: false,
  },
  {
    id: '510409826',
    thumbnail: 'https://i.vimeocdn.com/video/1062316507_295x166.jpg?r=pad',
    title: 'Stories In Place: Zionly Manna',
    author: '33BOUND',
    views: 'Unknown',
    likes: 208,
    iframe: '<iframe src="https://player.vimeo.com/video/510409826?badge=0&amp;autopause=0&amp;player_id=0&amp;app_id=210503" width="3840" height="2160" frameborder="0" allow="autoplay; fullscreen; picture-in-picture" allowfullscreen title="Stories In Place: Zionly Manna"></iframe>',
    dateAdded: '2014-12-18T23:18:12+01:00',
    platform: 'Vimeo',
    url: 'https://vimeo.com/510409826',
    isFavorite: false,
  },
  {
    id: 'uqzxnz6d7JM',
    thumbnail: 'https://i.ytimg.com/vi/uqzxnz6d7JM/mqdefault.jpg',
    title: 'Most Beautiful Chess Game Ever Played - "The Evergreen Game"',
    author: "agadmator's Chess Channel",
    views: '2136120',
    likes: '50236',
    iframe: "<iframe src='https://youtube.com/embed/uqzxnz6d7JM' \n                frameborder=\"0\" \n                allow=\"accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture\" \n                allowfullscreen \n                title=Most Beautiful Chess Game Ever Played - \"The Evergreen Game\"</iframe>",
    dateAdded: '2014-04-18T00:43:02+02:00',
    platform: 'YouTube',
    url: 'https://youtube.com/uqzxnz6d7JM',
    isFavorite: false,
  },
  {
    id: 'FTSsgtugF5w',
    thumbnail: 'https://i.ytimg.com/vi/FTSsgtugF5w/mqdefault.jpg',
    title: 'cat vs nemo',
    author: 'welf',
    views: '3874204',
    likes: '88788',
    iframe: "<iframe src='https://youtube.com/embed/FTSsgtugF5w' \n                frameborder=\"0\" \n                allow=\"accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture\" \n                allowfullscreen \n                title=cat vs nemo</iframe>",
    dateAdded: '2013-12-28T08:32:54+01:00',
    platform: 'YouTube',
    url: 'https://youtube.com/FTSsgtugF5w',
    isFavorite: false,
  },
  {
    id: '532396381',
    thumbnail: 'https://i.vimeocdn.com/video/1101752826_295x166.jpg?r=pad',
    title: 'Stranded',
    author: 'Stéphane RIDARD',
    views: 'Unknown',
    likes: 143,
    iframe: '<iframe src="https://player.vimeo.com/video/532396381?badge=0&amp;autopause=0&amp;player_id=0&amp;app_id=210503" width="3840" height="2160" frameborder="0" allow="autoplay; fullscreen; picture-in-picture" allowfullscreen title="Stranded"></iframe>',
    dateAdded: '2019-03-20T22:22:12+01:00',
    platform: 'Vimeo',
    url: 'https://vimeo.com/532396381',
    isFavorite: false,
  },
  {
    id: '531275866',
    thumbnail: 'https://i.vimeocdn.com/video/1099629567_295x166.jpg?r=pad',
    title: 'Pause Originals 2021 - Yin And Yang',
    author: 'Andrea Damiano // Sound Design',
    views: 'Unknown',
    likes: 42,
    iframe: '<iframe src="https://player.vimeo.com/video/531275866?badge=0&amp;autopause=0&amp;player_id=0&amp;app_id=210503" width="1920" height="1080" frameborder="0" allow="autoplay; fullscreen; picture-in-picture" allowfullscreen title="Pause Originals 2021 - Yin And Yang"></iframe>',
    dateAdded: '2019-06-01T04:25:05+02:00',
    platform: 'Vimeo',
    url: 'https://vimeo.com/531275866',
    isFavorite: true,
  },
  {
    id: 'M8fdi6TwFHY',
    thumbnail: 'https://i.ytimg.com/vi/M8fdi6TwFHY/mqdefault.jpg',
    title: 'My pet fly',
    author: 'z3eM Productions',
    views: '26060664',
    likes: '662647',
    iframe: "<iframe src='https://youtube.com/embed/M8fdi6TwFHY' \n                frameborder=\"0\" \n                allow=\"accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture\" \n                allowfullscreen \n                title=My pet fly</iframe>",
    dateAdded: '2014-08-09T09:37:21+02:00',
    platform: 'YouTube',
    url: 'https://youtube.com/M8fdi6TwFHY',
    isFavorite: true,
  },
  {
    id: 'L5uV3gmOH9g',
    thumbnail: 'https://i.ytimg.com/vi/L5uV3gmOH9g/mqdefault.jpg',
    title: 'Bring Me The Horizon - Teardrops (Official Video)',
    author: 'BMTHOfficialVEVO',
    views: '16574014',
    likes: '449751',
    iframe: "<iframe src='https://youtube.com/embed/L5uV3gmOH9g' \n                frameborder=\"0\" \n                allow=\"accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture\" \n                allowfullscreen \n                title=Bring Me The Horizon - Teardrops (Official Video)</iframe>",
    dateAdded: '2016-08-06T14:24:26+02:00',
    platform: 'YouTube',
    url: 'https://youtube.com/L5uV3gmOH9g',
    isFavorite: false,
  },
  {
    id: 'uBbwZCRIILM',
    thumbnail: 'https://i.ytimg.com/vi/uBbwZCRIILM/mqdefault.jpg',
    title: 'no u',
    author: 'narpy',
    views: '22233108',
    likes: '1045015',
    iframe: "<iframe src='https://youtube.com/embed/uBbwZCRIILM' \n                frameborder=\"0\" \n                allow=\"accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture\" \n                allowfullscreen \n                title=no u</iframe>",
    dateAdded: '2015-05-09T10:40:53+02:00',
    platform: 'YouTube',
    url: 'https://youtube.com/uBbwZCRIILM',
    isFavorite: false,
  },
  {
    id: '2sBFkfcB8WA',
    thumbnail: 'https://i.ytimg.com/vi/2sBFkfcB8WA/mqdefault.jpg',
    title: 'Badlands chugs the ocean',
    author: 'The Wrong Neighborhood',
    views: '35170277',
    likes: '939011',
    iframe: "<iframe src='https://youtube.com/embed/2sBFkfcB8WA' \n                frameborder=\"0\" \n                allow=\"accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture\" \n                allowfullscreen \n                title=Badlands chugs the ocean</iframe>",
    dateAdded: '2018-01-04T10:36:23+01:00',
    platform: 'YouTube',
    url: 'https://youtube.com/2sBFkfcB8WA',
    isFavorite: true,
  },
  {
    id: 'PLb720ZPcQI',
    thumbnail: 'https://i.ytimg.com/vi/PLb720ZPcQI/mqdefault.jpg',
    title: 'Cha cha real smooth',
    author: 'Pukekura',
    views: '18711933',
    likes: '791461',
    iframe: "<iframe src='https://youtube.com/embed/PLb720ZPcQI' \n                frameborder=\"0\" \n                allow=\"accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture\" \n                allowfullscreen \n                title=Cha cha real smooth</iframe>",
    dateAdded: '2011-01-28T02:18:50+01:00',
    platform: 'YouTube',
    url: 'https://youtube.com/PLb720ZPcQI',
    isFavorite: true,
  },
  {
    id: 'rb8z2BMrd60',
    thumbnail: 'https://i.ytimg.com/vi/rb8z2BMrd60/mqdefault.jpg',
    title: 'Original "Stop it, get some help" Michael Jordan Anti-drug PSA 1987',
    author: 'EightiesTV',
    views: '11811579',
    likes: '617487',
    iframe: "<iframe src='https://youtube.com/embed/rb8z2BMrd60' \n                frameborder=\"0\" \n                allow=\"accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture\" \n                allowfullscreen \n                title=Original \"Stop it, get some help\" Michael Jordan Anti-drug PSA 1987</iframe>",
    dateAdded: '2009-06-06T20:40:48+02:00',
    platform: 'YouTube',
    url: 'https://youtube.com/rb8z2BMrd60',
    isFavorite: false,
  },
  {
    id: '-qlp5x3V0xI',
    thumbnail: 'https://i.ytimg.com/vi/-qlp5x3V0xI/mqdefault.jpg',
    title: 'Molotov',
    author: 'Slipspace Entertainment',
    views: '24377453',
    likes: '995773',
    iframe: "<iframe src='https://youtube.com/embed/-qlp5x3V0xI' \n                frameborder=\"0\" \n                allow=\"accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture\" \n                allowfullscreen \n                title=Molotov</iframe>",
    dateAdded: '2013-02-17T01:50:52+01:00',
    platform: 'YouTube',
    url: 'https://youtube.com/-qlp5x3V0xI',
    isFavorite: true,
  },
  {
    id: '531387863',
    thumbnail: 'https://i.vimeocdn.com/video/1099822309_295x166.jpg?r=pad',
    title: 'Maison Hanko - Triple Jump, directed by Hideyuki Tanaka',
    author: 'Nexus Studios',
    views: 'Unknown',
    likes: 271,
    iframe: '<iframe src="https://player.vimeo.com/video/531387863?badge=0&amp;autopause=0&amp;player_id=0&amp;app_id=210503" width="1280" height="720" frameborder="0" allow="autoplay; fullscreen; picture-in-picture" allowfullscreen title="Maison Hanko - Triple Jump, directed by Hideyuki Tanaka"></iframe>',
    dateAdded: '2017-10-19T21:17:21+02:00',
    platform: 'Vimeo',
    url: 'https://vimeo.com/531387863',
    isFavorite: false,
  },
  {
    id: 'LBQ-4DPn_0Y',
    thumbnail: 'https://i.ytimg.com/vi/LBQ-4DPn_0Y/mqdefault.jpg',
    title: 'Shot on iPhone meme',
    author: 'Gamingstar',
    views: '29232195',
    likes: '745739',
    iframe: "<iframe src='https://youtube.com/embed/LBQ-4DPn_0Y' \n                frameborder=\"0\" \n                allow=\"accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture\" \n                allowfullscreen \n                title=Shot on iPhone meme</iframe>",
    dateAdded: '2018-04-01T05:15:48+02:00',
    platform: 'YouTube',
    url: 'https://youtube.com/LBQ-4DPn_0Y',
    isFavorite: false,
  },
  {
    id: 'fZy6dWq7zA0',
    thumbnail: 'https://i.ytimg.com/vi/fZy6dWq7zA0/mqdefault.jpg',
    title: 'Sonic Plays Rocket League',
    author: 'TotallyNotPatrick',
    views: '5689388',
    likes: '76056',
    iframe: "<iframe src='https://youtube.com/embed/fZy6dWq7zA0' \n                frameborder=\"0\" \n                allow=\"accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture\" \n                allowfullscreen \n                title=Sonic Plays Rocket League</iframe>",
    dateAdded: '2021-02-10T15:25:18+01:00',
    platform: 'YouTube',
    url: 'https://youtube.com/fZy6dWq7zA0',
    isFavorite: false,
  },
  {
    id: '534551768',
    thumbnail: 'https://i.vimeocdn.com/video/1109601801_295x166.jpg?r=pad',
    title: 'Dapper Dan and the COVID-19 Vaccines',
    author: 'sperry',
    views: 'Unknown',
    likes: 27,
    iframe: '<iframe src="https://player.vimeo.com/video/534551768?badge=0&amp;autopause=0&amp;player_id=0&amp;app_id=210503" width="2944" height="2160" frameborder="0" allow="autoplay; fullscreen; picture-in-picture" allowfullscreen title="Dapper Dan and the COVID-19 Vaccines"></iframe>',
    dateAdded: '2012-04-09T20:29:09+02:00',
    platform: 'Vimeo',
    url: 'https://vimeo.com/534551768',
    isFavorite: false,
  },
  {
    id: '309219554',
    thumbnail: 'https://i.vimeocdn.com/video/1075308976_295x166.jpg?r=pad',
    title: 'Across, Beyond, and Over',
    author: 'Brit Fryer',
    views: 'Unknown',
    likes: 229,
    iframe: '<iframe src="https://player.vimeo.com/video/309219554?badge=0&amp;autopause=0&amp;player_id=0&amp;app_id=210503" width="1920" height="1080" frameborder="0" allow="autoplay; fullscreen; picture-in-picture" allowfullscreen title="Across, Beyond, and Over"></iframe>',
    dateAdded: '2012-05-21T05:13:26+02:00',
    platform: 'Vimeo',
    url: 'https://vimeo.com/309219554',
    isFavorite: false,
  },
  {
    id: '-Hl1a57X7Cg',
    thumbnail: 'https://i.ytimg.com/vi/-Hl1a57X7Cg/mqdefault.jpg',
    title: 'Pointy Features x Kanisan x Softy - Shine On 🌙 [lofi hip hop/relaxing beats]',
    author: 'Lofi Girl',
    views: '37002',
    likes: '2379',
    iframe: "<iframe src='https://youtube.com/embed/-Hl1a57X7Cg' \n                frameborder=\"0\" \n                allow=\"accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture\" \n                allowfullscreen \n                title=Pointy Features x Kanisan x Softy - Shine On 🌙 [lofi hip hop/relaxing beats]</iframe>",
    dateAdded: '2018-11-15T08:53:42+01:00',
    platform: 'YouTube',
    url: 'https://youtube.com/-Hl1a57X7Cg',
    isFavorite: false,
  },
  {
    id: '521629477',
    thumbnail: 'https://i.vimeocdn.com/video/1080381839_295x166.jpg?r=pad',
    title: 'Goodbye Golovin by Mathieu Grimard',
    author: 'Math Grimard',
    views: 'Unknown',
    likes: 815,
    iframe: '<iframe src="https://player.vimeo.com/video/521629477?badge=0&amp;autopause=0&amp;player_id=0&amp;app_id=210503" width="1920" height="1080" frameborder="0" allow="autoplay; fullscreen; picture-in-picture" allowfullscreen title="Goodbye Golovin by Mathieu Grimard"></iframe>',
    dateAdded: '2009-05-26T05:47:26+02:00',
    platform: 'Vimeo',
    url: 'https://vimeo.com/521629477',
    isFavorite: true,
  },
  {
    id: '531825168',
    thumbnail: 'https://i.vimeocdn.com/video/1100673691_295x166.jpg?r=pad',
    title: 'CHASING GHOSTS | OFFICIAL SCREENER | © GRIZZLY CREEK FILMS',
    author: 'Grizzly Creek Films',
    views: 'Unknown',
    likes: 195,
    iframe: '<iframe src="https://player.vimeo.com/video/531825168?badge=0&amp;autopause=0&amp;player_id=0&amp;app_id=210503" width="1920" height="1080" frameborder="0" allow="autoplay; fullscreen; picture-in-picture" allowfullscreen title="CHASING GHOSTS | OFFICIAL SCREENER | &amp;copy; GRIZZLY CREEK FILMS"></iframe>',
    dateAdded: '2011-09-14T23:09:54+02:00',
    platform: 'Vimeo',
    url: 'https://vimeo.com/531825168',
    isFavorite: false,
  },
  {
    id: '531368853',
    thumbnail: 'https://i.vimeocdn.com/video/1103912295_295x166.jpg?r=pad',
    title: 'Inland Empire',
    author: 'Zane Rubin',
    views: 'Unknown',
    likes: 194,
    iframe: '<iframe src="https://player.vimeo.com/video/531368853?badge=0&amp;autopause=0&amp;player_id=0&amp;app_id=210503" width="1920" height="1080" frameborder="0" allow="autoplay; fullscreen; picture-in-picture" allowfullscreen title="Inland Empire"></iframe>',
    dateAdded: '2010-01-24T01:13:13+01:00',
    platform: 'Vimeo',
    url: 'https://vimeo.com/531368853',
    isFavorite: false,
  },
  {
    id: 'Obgnr9pc820',
    thumbnail: 'https://i.ytimg.com/vi/Obgnr9pc820/mqdefault.jpg',
    title: 'Hi Okay',
    author: 'Lili H',
    views: '54639673',
    likes: '1183380',
    iframe: "<iframe src='https://youtube.com/embed/Obgnr9pc820' \n                frameborder=\"0\" \n                allow=\"accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture\" \n                allowfullscreen \n                title=Hi Okay</iframe>",
    dateAdded: '2010-08-19T00:06:15+02:00',
    platform: 'YouTube',
    url: 'https://youtube.com/Obgnr9pc820',
    isFavorite: false,
  },
  {
    id: 'T3W4Mx2aSGE',
    thumbnail: 'https://i.ytimg.com/vi/T3W4Mx2aSGE/mqdefault.jpg',
    title: 'kevin interrupts ann',
    author: 'kmlkmljkl',
    views: '11478613',
    likes: '406249',
    iframe: "<iframe src='https://youtube.com/embed/T3W4Mx2aSGE' \n                frameborder=\"0\" \n                allow=\"accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture\" \n                allowfullscreen \n                title=kevin interrupts ann</iframe>",
    dateAdded: '2013-06-24T05:33:45+02:00',
    platform: 'YouTube',
    url: 'https://youtube.com/T3W4Mx2aSGE',
    isFavorite: true,
  },
  {
    id: 'aANF2OOVX40',
    thumbnail: 'https://i.ytimg.com/vi/aANF2OOVX40/mqdefault.jpg',
    title: 'Interstellar Mouse',
    author: 'Dankius M. Meme',
    views: '11821750',
    likes: '391581',
    iframe: "<iframe src='https://youtube.com/embed/aANF2OOVX40' \n                frameborder=\"0\" \n                allow=\"accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture\" \n                allowfullscreen \n                title=Interstellar Mouse</iframe>",
    dateAdded: '2019-03-04T15:30:43+01:00',
    platform: 'YouTube',
    url: 'https://youtube.com/aANF2OOVX40',
    isFavorite: false,
  },
  {
    id: 'T4P0-7BXlao',
    thumbnail: 'https://i.ytimg.com/vi/T4P0-7BXlao/mqdefault.jpg',
    title: 'Believe in the dream ~ lofi hip hop mix]',
    author: 'Dreamy',
    views: '14162',
    likes: '912',
    iframe: "<iframe src='https://youtube.com/embed/T4P0-7BXlao' \n                frameborder=\"0\" \n                allow=\"accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture\" \n                allowfullscreen \n                title=Believe in the dream ~ lofi hip hop mix]</iframe>",
    dateAdded: '2014-02-24T05:56:15+01:00',
    platform: 'YouTube',
    url: 'https://youtube.com/T4P0-7BXlao',
    isFavorite: true,
  },
  {
    id: '518404753',
    thumbnail: 'https://i.vimeocdn.com/video/1074209226_295x166.jpg?r=pad',
    title: 'From My Window',
    author: 'Futuristic Films',
    views: 'Unknown',
    likes: 541,
    iframe: '<iframe src="https://player.vimeo.com/video/518404753?badge=0&amp;autopause=0&amp;player_id=0&amp;app_id=210503" width="1920" height="1080" frameborder="0" allow="autoplay; fullscreen; picture-in-picture" allowfullscreen title="From My Window"></iframe>',
    dateAdded: '2009-10-28T11:21:15+01:00',
    platform: 'Vimeo',
    url: 'https://vimeo.com/518404753',
    isFavorite: false,
  },
  {
    id: 'ayCglHI8ltw',
    thumbnail: 'https://i.ytimg.com/vi/ayCglHI8ltw/mqdefault.jpg',
    title: 'Alternative Rock Of The 2000s 2000 2009 Metallica , Cranberries, Creed, 3 Doors Down, Nirvana',
    author: 'Music Collection',
    views: '13793125',
    likes: '114614',
    iframe: "<iframe src='https://youtube.com/embed/ayCglHI8ltw' \n                frameborder=\"0\" \n                allow=\"accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture\" \n                allowfullscreen \n                title=Alternative Rock Of The 2000s 2000 2009 Metallica , Cranberries, Creed, 3 Doors Down, Nirvana</iframe>",
    dateAdded: '2018-05-22T05:47:08+02:00',
    platform: 'YouTube',
    url: 'https://youtube.com/ayCglHI8ltw',
    isFavorite: false,
  },
  {
    id: '531817045',
    thumbnail: 'https://i.vimeocdn.com/video/1100654071_295x166.jpg?r=pad',
    title: 'How it Happened - Blackout at the Super Bowl [Presented by TurboTax]',
    author: 'Yuvaroo',
    views: 'Unknown',
    likes: 14,
    iframe: '<iframe src="https://player.vimeo.com/video/531817045?badge=0&amp;autopause=0&amp;player_id=0&amp;app_id=210503" width="1920" height="1080" frameborder="0" allow="autoplay; fullscreen; picture-in-picture" allowfullscreen title="How it Happened - Blackout at the Super Bowl [Presented by TurboTax]"></iframe>',
    dateAdded: '2012-09-26T20:14:37+02:00',
    platform: 'Vimeo',
    url: 'https://vimeo.com/531817045',
    isFavorite: false,
  },
  {
    id: 'QJJWmBlONIQ',
    thumbnail: 'https://i.ytimg.com/vi/QJJWmBlONIQ/mqdefault.jpg',
    title: "\"All Star\" by Smashmouth but it's Sung by Kermit",
    author: 'GeekHeavy',
    views: '2201651',
    likes: '56002',
    iframe: "<iframe src='https://youtube.com/embed/QJJWmBlONIQ' \n                frameborder=\"0\" \n                allow=\"accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture\" \n                allowfullscreen \n                title=\"All Star\" by Smashmouth but it's Sung by Kermit</iframe>",
    dateAdded: '2011-11-15T18:39:38+01:00',
    platform: 'YouTube',
    url: 'https://youtube.com/QJJWmBlONIQ',
    isFavorite: false,
  },
  {
    id: '491339383',
    thumbnail: 'https://i.vimeocdn.com/video/1016213574_295x166.jpg?r=pad',
    title: 'Found Me',
    author: 'David Findlay',
    views: 'Unknown',
    likes: 1208,
    iframe: '<iframe src="https://player.vimeo.com/video/491339383?badge=0&amp;autopause=0&amp;player_id=0&amp;app_id=210503" width="1920" height="1080" frameborder="0" allow="autoplay; fullscreen; picture-in-picture" allowfullscreen title="Found Me"></iframe>',
    dateAdded: '2016-07-14T02:12:58+02:00',
    platform: 'Vimeo',
    url: 'https://vimeo.com/491339383',
    isFavorite: false,
  },
  {
    id: '1Eg11wm77ZY',
    thumbnail: 'https://i.ytimg.com/vi/1Eg11wm77ZY/mqdefault.jpg',
    title: 'checkm8',
    author: 'Dave',
    views: '1132105',
    likes: '35254',
    iframe: "<iframe src='https://youtube.com/embed/1Eg11wm77ZY' \n                frameborder=\"0\" \n                allow=\"accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture\" \n                allowfullscreen \n                title=checkm8</iframe>",
    dateAdded: '2014-08-24T11:56:16+02:00',
    platform: 'YouTube',
    url: 'https://youtube.com/1Eg11wm77ZY',
    isFavorite: false,
  },
  {
    id: 'AyOqGRjVtls',
    thumbnail: 'https://i.ytimg.com/vi/AyOqGRjVtls/mqdefault.jpg',
    title: 'Kermit is Never Gonna Give You Up',
    author: 'GeekHeavy',
    views: '4962057',
    likes: '218371',
    iframe: "<iframe src='https://youtube.com/embed/AyOqGRjVtls' \n                frameborder=\"0\" \n                allow=\"accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture\" \n                allowfullscreen \n                title=Kermit is Never Gonna Give You Up</iframe>",
    dateAdded: '2017-11-20T18:39:33+01:00',
    platform: 'YouTube',
    url: 'https://youtube.com/AyOqGRjVtls',
    isFavorite: false,
  },
  {
    id: '483817264',
    thumbnail: 'https://i.vimeocdn.com/video/1002498060_295x166.jpg?r=pad',
    title: 'FAREWELL, WORK HOLIDAY PARTIES, 2020 by Alex Prager',
    author: 'Alex Prager Studio',
    views: 'Unknown',
    likes: 214,
    iframe: '<iframe src="https://player.vimeo.com/video/483817264?badge=0&amp;autopause=0&amp;player_id=0&amp;app_id=210503" width="1920" height="1080" frameborder="0" allow="autoplay; fullscreen; picture-in-picture" allowfullscreen title="FAREWELL, WORK HOLIDAY PARTIES, 2020 by Alex Prager"></iframe>',
    dateAdded: '2015-01-30T09:20:56+01:00',
    platform: 'Vimeo',
    url: 'https://vimeo.com/483817264',
    isFavorite: true,
  },
  {
    id: '-Z4jx5VMw8M',
    thumbnail: 'https://i.ytimg.com/vi/-Z4jx5VMw8M/mqdefault.jpg',
    title: "Cat Can't Handle Flower",
    author: 'DailyPicksandFlicks',
    views: '24830709',
    likes: '875564',
    iframe: "<iframe src='https://youtube.com/embed/-Z4jx5VMw8M' \n                frameborder=\"0\" \n                allow=\"accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture\" \n                allowfullscreen \n                title=Cat Can't Handle Flower</iframe>",
    dateAdded: '2010-10-16T10:28:37+02:00',
    platform: 'YouTube',
    url: 'https://youtube.com/-Z4jx5VMw8M',
    isFavorite: true,
  },
  {
    id: 'c7BVtGnlxT8',
    thumbnail: 'https://i.ytimg.com/vi/c7BVtGnlxT8/mqdefault.jpg',
    title: 'why do I hear boss music?',
    author: 'Daniyal Shahrokhian',
    views: '8218069',
    likes: '402401',
    iframe: "<iframe src='https://youtube.com/embed/c7BVtGnlxT8' \n                frameborder=\"0\" \n                allow=\"accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture\" \n                allowfullscreen \n                title=why do I hear boss music?</iframe>",
    dateAdded: '2018-11-04T12:52:31+01:00',
    platform: 'YouTube',
    url: 'https://youtube.com/c7BVtGnlxT8',
    isFavorite: true,
  },
  {
    id: '533729157',
    thumbnail: 'https://i.vimeocdn.com/video/1104824432_295x166.jpg?r=pad',
    title: 'The Journey | UNHCR',
    author: 'Pantera',
    views: 'Unknown',
    likes: 516,
    iframe: '<iframe src="https://player.vimeo.com/video/533729157?badge=0&amp;autopause=0&amp;player_id=0&amp;app_id=210503" width="1920" height="1080" frameborder="0" allow="autoplay; fullscreen; picture-in-picture" allowfullscreen title="The Journey | UNHCR"></iframe>',
    dateAdded: '2013-04-26T10:00:00+02:00',
    platform: 'Vimeo',
    url: 'https://vimeo.com/533729157',
    isFavorite: false,
  },
];

export default SampleVideos;
